### ISSUE TITLE
Problem on macOS with gfortran

### ISSUE THREAD

**Issue by gha3mi** [awvwgk/setup-fortran#32]
Thanks for the project.

There is a problem with the mac operating system. It appears that it only works with gfortran version 10.

When running a simple `fpm test` on mac using gfortran, I encountered this error:

It seems that it works only with gfortran 10.
```shell
 dyld[2196]: Library not loaded: '/usr/local/opt/gcc@10/lib/gcc/10/libgfortran.5.dylib'
  Referenced from: '/Users/runner/work/_temp/fpm'
  Reason: tried: '/usr/local/opt/gcc@10/lib/gcc/10/libgfortran.5.dylib' (no such file), '/usr/local/lib/libgfortran.5.dylib' (no such file), '/usr/lib/libgfortran.5.dylib' (no such file)
/Users/runner/work/_temp/378df7c3-1bf9-413a-8a60-858cb91f887e.sh: line 1:  2196 Abort trap: 6           fpm test
Error: Process completed with exit code 134.
```

To temporarily solve the problem, I used the following steps:

```yml
    - name: Setup Fortran on Windows
      if: contains( matrix.os, 'windows')
      uses: awvwgk/setup-fortran@v1
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - name: Setup Fortran on MacOS
      if: contains( matrix.os, 'macos')
      run: |
        brew reinstall gcc@12
        ln -s /usr/local/lib/gcc/current/libgfortran.5.dylib /usr/local/lib/
        ln -s /usr/local/lib/gcc/current/libquadmath.0.dylib /usr/local/lib/
        ln -s /usr/local/Cellar/gcc/13.1.0/bin/gfortran /usr/local/bin/gfortran
        # ln -s /usr/local/lib/gcc/current/bin/gfortran /usr/local/bin/gfortran
```
